-- H2 Test Schema for DetroitChow Admin
-- This schema is used for testing only

CREATE SCHEMA IF NOT EXISTS detroitchow;

-- Locations table
CREATE TABLE IF NOT EXISTS detroitchow.locations (
    locationid VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    operating_status VARCHAR(50) DEFAULT 'active',
    address1 VARCHAR(500),
    address2 VARCHAR(500),
    city VARCHAR(100),
    locality VARCHAR(100),
    zip VARCHAR(100),
    region VARCHAR(100),
    country VARCHAR(2),
    phone1 VARCHAR(20),
    phone2 VARCHAR(20),
    lat VARCHAR(100),
    lng VARCHAR(100),
    website VARCHAR(2000),
    facebook VARCHAR(2000),
    twitter VARCHAR(2000),
    instagram VARCHAR(2000),
    opentable VARCHAR(2000),
    tripadvisor VARCHAR(2000),
    yelp VARCHAR(2000),
    hours VARCHAR(2000),
    contact_text VARCHAR(2000),
    create_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    create_user VARCHAR(100),
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_user VARCHAR(100)
);

-- Menus table
CREATE TABLE IF NOT EXISTS detroitchow.menus (
    locationid VARCHAR(50) NOT NULL,
    menu_link VARCHAR(2000) NOT NULL,
    image VARCHAR(2000),
    priority INTEGER DEFAULT 0,
    descr VARCHAR(500),
    create_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    create_user VARCHAR(100),
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_user VARCHAR(100),
    PRIMARY KEY (locationid, menu_link),
    FOREIGN KEY (locationid) REFERENCES detroitchow.locations(locationid) ON DELETE CASCADE
);

-- Google Places table
CREATE TABLE IF NOT EXISTS detroitchow.google_places (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locationid VARCHAR(50) NOT NULL,
    place_id VARCHAR(500) NOT NULL,
    name VARCHAR(500),
    lat VARCHAR(50),
    lng VARCHAR(50),
    phone1 VARCHAR(500),
    phone2 VARCHAR(500),
    formatted_address VARCHAR(1000),
    website VARCHAR(1000),
    google_url VARCHAR(1000),
    business_status VARCHAR(50),
    txtsearch_json JSON,
    detail_json JSON,
    store_json JSON,
    premise_place_id VARCHAR(500),
    store_place_id VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_locations_operating_status ON detroitchow.locations(operating_status);
CREATE INDEX IF NOT EXISTS idx_locations_city ON detroitchow.locations(city);
CREATE INDEX IF NOT EXISTS idx_locations_region ON detroitchow.locations(region);
CREATE INDEX IF NOT EXISTS idx_locations_country ON detroitchow.locations(country);
CREATE INDEX IF NOT EXISTS idx_locations_locality ON detroitchow.locations(locality);
CREATE INDEX IF NOT EXISTS idx_locations_status_city ON detroitchow.locations(operating_status, city);
