/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all Detroit Chow locations
         * @description Returns a list of all Detroit Chow restaurant locations
         */
        get: operations["getAllLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific Detroit Chow location
         * @description Returns detailed information for a specific location by ID
         */
        get: operations["getLocationById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a Detroit Chow location
         * @description Updates all fields for a given Detroit Chow location
         */
        put: operations["updateLocation"];
        /**
         * Create a new Detroit Chow location
         * @description Creates a new Detroit Chow restaurant location
         */
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location/{locationId}/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all menus for a location
         * @description Returns all menus for a specific location, ordered by priority
         */
        get: operations["getLocationMenus"];
        put?: never;
        /**
         * Add a menu to a location
         * @description Adds a new menu to a location
         */
        post: operations["addMenuToLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location/{locationId}/menus/{menuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific menu
         * @description Returns a specific menu by location and menu ID
         */
        get: operations["getMenu"];
        /**
         * Update a menu
         * @description Updates a menu's information including priority
         */
        put: operations["updateMenu"];
        post?: never;
        /**
         * Delete a menu
         * @description Removes a menu from a location
         */
        delete: operations["deleteMenu"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location/{locationId}/menus/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder menus by priority
         * @description Updates the priority/order of multiple menus at once
         */
        post: operations["reorderMenus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Detroit Chow location with all fields including menus and Google Places data */
        Location: {
            /**
             * @description Unique identifier for the location
             * @example loc_12345
             */
            locationid: string;
            /**
             * @description Restaurant name
             * @example Joe's Pizza
             */
            name: string;
            /** @description Description of the restaurant */
            description?: string | null;
            /**
             * @description Current status of the location
             * @default active
             * @enum {string}
             */
            status: "active" | "temporarily_closed" | "permanently_closed";
            /**
             * @description Primary address line
             * @example 123 Main Street
             */
            address1: string;
            /** @description Secondary address line (apartment, suite, etc.) */
            address2?: string | null;
            /**
             * @description City name
             * @example Detroit
             */
            city: string;
            /** @description Locality or neighborhood */
            locality?: string | null;
            /**
             * @description ZIP/Postal code
             * @example 48201
             */
            zip: string;
            /**
             * @description State or province
             * @example Michigan
             */
            region: string;
            /**
             * @description Country name
             * @default United States
             * @example United States
             */
            country: string;
            /**
             * @description Primary phone number
             * @example +1-313-555-1234
             */
            phone1?: string | null;
            /** @description Secondary phone number */
            phone2?: string | null;
            /**
             * Format: double
             * @description Latitude coordinate
             * @example 42.3314
             */
            lat?: number;
            /**
             * Format: double
             * @description Longitude coordinate
             * @example -83.0458
             */
            lng?: number;
            /**
             * Format: uri
             * @description Restaurant website URL
             */
            website?: string | null;
            /**
             * Format: uri
             * @description Facebook page URL
             */
            facebook?: string | null;
            /**
             * Format: uri
             * @description Twitter/X profile URL
             */
            twitter?: string | null;
            /**
             * Format: uri
             * @description Instagram profile URL
             */
            instagram?: string | null;
            /**
             * Format: uri
             * @description OpenTable reservation link
             */
            opentable?: string | null;
            /**
             * Format: uri
             * @description TripAdvisor page URL
             */
            tripadvisor?: string | null;
            /**
             * Format: uri
             * @description Yelp business page URL
             */
            yelp?: string | null;
            /** @description Operating hours (format TBD - may be structured in future) */
            hours?: string | null;
            /** @description Contact information text */
            contact_text?: string | null;
            /** @description Array of menus associated with this location, ordered by priority */
            menus?: components["schemas"]["Menu"][];
            googlePlaces?: components["schemas"]["GooglePlaces"];
        };
        /** @description Input schema for creating a new location (locationid not required on creation) */
        LocationInput: {
            /** @description Restaurant name */
            name: string;
            /** @description Description of the restaurant */
            description?: string | null;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "temporarily_closed" | "permanently_closed";
            /** @description Primary address line */
            address1: string;
            /** @description Secondary address line */
            address2?: string | null;
            /** @description City name */
            city: string;
            /** @description Locality or neighborhood */
            locality?: string | null;
            /** @description ZIP/Postal code */
            zip: string;
            /** @description State or province */
            region: string;
            /**
             * @description Country name
             * @default United States
             */
            country: string;
            /** @description Primary phone number */
            phone1?: string | null;
            /** @description Secondary phone number */
            phone2?: string | null;
            /**
             * Format: double
             * @description Latitude coordinate
             */
            lat?: number;
            /**
             * Format: double
             * @description Longitude coordinate
             */
            lng?: number;
            /**
             * Format: uri
             * @description Restaurant website URL
             */
            website?: string | null;
            /**
             * Format: uri
             * @description Facebook page URL
             */
            facebook?: string | null;
            /**
             * Format: uri
             * @description Twitter/X profile URL
             */
            twitter?: string | null;
            /**
             * Format: uri
             * @description Instagram profile URL
             */
            instagram?: string | null;
            /**
             * Format: uri
             * @description OpenTable reservation link
             */
            opentable?: string | null;
            /**
             * Format: uri
             * @description TripAdvisor page URL
             */
            tripadvisor?: string | null;
            /**
             * Format: uri
             * @description Yelp business page URL
             */
            yelp?: string | null;
            /** @description Operating hours */
            hours?: string | null;
            /** @description Contact information text */
            contact_text?: string | null;
            /** @description Array of menus associated with this location */
            menus?: components["schemas"]["MenuInput"][];
            googlePlaces?: components["schemas"]["GooglePlacesInput"];
        };
        /** @description Menu associated with a Detroit Chow location */
        Menu: {
            /**
             * @description Description of the menu
             * @example Lunch Menu
             */
            descr?: string | null;
            /**
             * Format: uri
             * @description URL to the menu (PDF, image, or external link)
             * @example https://detroitchow.com/menus/lunch-menu.pdf
             */
            menu_link?: string | null;
            /**
             * @description Display priority for ordering menus (lower number = higher priority/displayed first)
             * @example 1
             */
            priority: number;
        };
        /** @description Input schema for creating or updating a menu */
        MenuInput: {
            /** @description Description of the menu */
            descr?: string | null;
            /**
             * Format: uri
             * @description URL to the menu (PDF, image, or external link)
             */
            menu_link?: string | null;
            /** @description Display priority for ordering menus (lower number = higher priority/displayed first) */
            priority: number;
        };
        /** @description Google Places data associated with a location */
        GooglePlaces: {
            /**
             * @description Google Places API place ID
             * @example ChIJN1blFLsB6IkRv5ZSZsJVHmM
             */
            place_id?: string;
            /** @description Business name from Google Places */
            name?: string;
            /**
             * Format: double
             * @description Latitude from Google Places
             */
            lat?: number;
            /**
             * Format: double
             * @description Longitude from Google Places
             */
            lng?: number;
            /** @description Primary phone number from Google Places */
            phone1?: string | null;
            /** @description Secondary phone number from Google Places */
            phone2?: string | null;
            /** @description Formatted address from Google Places */
            formatted_address?: string;
            /**
             * Format: uri
             * @description Website URL from Google Places
             */
            website?: string | null;
            /**
             * Format: uri
             * @description Google Maps business URL
             */
            google_url?: string | null;
            /**
             * @description Current business status from Google Places
             * @enum {string}
             */
            business_status?: "OPERATIONAL" | "CLOSED_TEMPORARILY" | "CLOSED_PERMANENTLY";
            /** @description Raw JSON response from Google Places Text Search API */
            txtsearch_json?: {
                [key: string]: unknown;
            } | null;
            /** @description Raw JSON response from Google Places Detail Search API */
            detail_json?: {
                [key: string]: unknown;
            } | null;
            /** @description Raw JSON response from Google Places Nearby Search API */
            store_json?: {
                [key: string]: unknown;
            } | null;
        } | null;
        /** @description Google Places data input (for creation/updates) */
        GooglePlacesInput: {
            /** @description Google Places API place ID */
            place_id?: string;
            /** @description Business name from Google Places */
            name?: string;
            /**
             * Format: double
             * @description Latitude from Google Places
             */
            lat?: number;
            /**
             * Format: double
             * @description Longitude from Google Places
             */
            lng?: number;
            /** @description Primary phone number from Google Places */
            phone1?: string | null;
            /** @description Secondary phone number from Google Places */
            phone2?: string | null;
            /** @description Formatted address from Google Places */
            formatted_address?: string;
            /**
             * Format: uri
             * @description Website URL from Google Places
             */
            website?: string | null;
            /**
             * Format: uri
             * @description Google Maps business URL
             */
            google_url?: string | null;
            /**
             * @description Current business status from Google Places
             * @enum {string}
             */
            business_status?: "OPERATIONAL" | "CLOSED_TEMPORARILY" | "CLOSED_PERMANENTLY";
            /** @description Raw JSON response from Google Places Text Search API */
            txtsearch_json?: {
                [key: string]: unknown;
            } | null;
            /** @description Raw JSON response from Google Places Detail Search API */
            detail_json?: {
                [key: string]: unknown;
            } | null;
            /** @description Raw JSON response from Google Places Nearby Search API */
            store_json?: {
                [key: string]: unknown;
            } | null;
        } | null;
        Error: {
            /** @description Error code */
            code: string;
            /** @description Human-readable error message */
            message: string;
            /** @description Additional error details */
            details?: Record<string, never> | null;
        };
    };
    responses: {
        /** @description Bad Request - Invalid input parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BAD_REQUEST",
                 *       "message": "Invalid request body",
                 *       "details": {
                 *         "field": "name",
                 *         "reason": "Name is required"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not Found - Resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Location not found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INTERNAL_SERVER_ERROR",
                 *       "message": "An unexpected error occurred"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved all locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"][];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getLocationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The location ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved the location */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Location"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Location object with updated information */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Location"];
            };
        };
        responses: {
            /** @description Location successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Location"];
                        /** @example Location updated successfully */
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Location object to be created */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationInput"];
            };
        };
        responses: {
            /** @description Location successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Location"];
                        /** @example Location created successfully */
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getLocationMenus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The location ID */
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved menus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Menu"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addMenuToLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The location ID */
                locationId: string;
            };
            cookie?: never;
        };
        /** @description Menu object to be added */
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuInput"];
            };
        };
        responses: {
            /** @description Menu successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Menu"];
                        /** @example Menu added successfully */
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
                menuId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved the menu */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Menu"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
                menuId: string;
            };
            cookie?: never;
        };
        /** @description Menu object with updated information */
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuInput"];
            };
        };
        responses: {
            /** @description Menu successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Menu"];
                        /** @example Menu updated successfully */
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
                menuId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Menu successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reorderMenus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: string;
            };
            cookie?: never;
        };
        /** @description Array of menu IDs in desired priority order */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Array of menu IDs in order (first item = highest priority)
                     * @example [
                     *       "menu_001",
                     *       "menu_002",
                     *       "menu_003"
                     *     ]
                     */
                    menuIds: string[];
                };
            };
        };
        responses: {
            /** @description Menus successfully reordered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Menu"][];
                        /** @example Menus reordered successfully */
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
